### ISSUE TITLE
Wind direction interpretation clearly not degrees

### ISSUE THREAD

**Issue by phillipjohnston** [sparkfun/MicroMod_Weather_Carrier_Board#3]
Is the wind direction supposed to correspond to degrees? When I try to use the example with an ESP32, 75% of the range returns a value of -1, and the remaining 25% is all over the place. With an Artemis, I only get numbers in specific ranges - never anything representing 0-180.

**Comment by makin-stuff** [comment]
Hello @phillipjohnston. Are you plugging in a weather meter to the RJ11 jacks?  The hardware and Arduino examples are designed specifically for this one: https://www.sparkfun.com/products/15901

**Comment by phillipjohnston** [comment]
Yep, that's the one I'm using! And indeed plugged into the RJ11 jacks.

**Comment by phillipjohnston** [comment]
I am using `MM_Weather_CB_Test` to check this behavior. With the latest Apollo3 board files update, the behavior is different. I now see values in the range of [0, 300] (never get above 300). However, the wind direction still does not seem to correspond to a consistent set of readings as far as I can tell - for example, I can never find any degrees above 300, and there only seems to be a few values that ever get reported, regardless of how precisely I turn the wind vane: 113, 23, 224, 248 are common values that appear. It is hard to see anything obvious in this from the log without a corresponding video setup showing how things are being turned on the weather vane... but I do not have a good recording setup to get all of that.

Log sample:

```
10:34:41.746 -> Temperature: 79.39
10:34:41.746 -> Humidity: 31
10:34:41.784 -> Pressure: 88734
10:34:41.784 -> Altitude: 3625.9
10:34:41.784 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:34:41.784 -> Soil Moisture = 122
10:34:41.784 -> Wind direction: 113 degrees
10:34:44.817 -> 
10:34:47.851 -> 
10:34:47.851 -> Temperature: 79.38
10:34:47.851 -> Humidity: 31
10:34:47.851 -> Pressure: 88730
10:34:47.851 -> Altitude: 3627.2
10:34:47.851 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:34:47.851 -> Soil Moisture = 173
10:34:47.885 -> Wind direction: 23 degrees
10:34:47.885 -> Rain click!
10:34:47.885 -> Disturber.
10:34:50.889 -> 
10:34:53.958 -> 
10:34:56.985 -> 
10:34:56.985 -> Temperature: 79.34
10:34:56.985 -> Humidity: 31
10:34:56.985 -> Pressure: 88730
10:34:56.985 -> Altitude: 3626.9
10:34:56.985 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:34:56.985 -> Soil Moisture = 200
10:34:57.019 -> Wind direction: 45 degrees
10:34:57.019 -> Rain click!
10:35:00.022 -> 
10:35:00.022 -> Temperature: 79.34
10:35:00.022 -> Humidity: 31
10:35:00.022 -> Pressure: 88727
10:35:00.022 -> Altitude: 3628.0
10:35:00.022 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:35:00.060 -> Soil Moisture = 132
10:35:00.060 -> Wind direction: 0 degrees
10:35:03.090 -> 
10:35:03.090 -> Temperature: 79.32
10:35:03.090 -> Humidity: 31
10:35:03.090 -> Pressure: 88731
10:35:03.090 -> Altitude: 3626.7
10:35:03.090 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:35:03.090 -> Soil Moisture = 252
10:35:03.090 -> Wind direction: 0 degrees
10:35:06.123 -> 
10:35:09.157 -> 
10:35:12.209 -> Temperature: 79.27
10:35:12.209 -> Humidity: 31
10:35:12.209 -> Pressure: 88733
10:35:12.209 -> Altitude: 3626.0
10:35:12.209 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:35:12.209 -> Soil Moisture = 219
10:35:12.242 -> Wind direction: 23 degrees
10:35:12.242 -> Rain click!
10:35:12.242 -> Disturber.
10:35:15.237 -> 
10:35:18.285 -> 
10:35:24.386 -> 
10:35:30.474 -> 
10:35:42.651 -> 
10:35:48.727 -> 
10:36:13.090 -> 
10:36:16.139 -> 
10:36:16.139 -> Temperature: 79.32
10:36:16.139 -> Humidity: 31
10:36:16.139 -> Pressure: 88731
10:36:16.139 -> Altitude: 3626.7
10:36:16.139 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:16.139 -> Soil Moisture = 254
10:36:16.139 -> Wind direction: 248 degrees
10:36:16.139 -> Rain click!
10:36:19.171 -> 
10:36:25.269 -> 
10:36:25.269 -> Temperature: 79.30
10:36:25.269 -> Humidity: 31
10:36:25.269 -> Pressure: 88730
10:36:25.269 -> Altitude: 3627.1
10:36:25.269 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:25.269 -> Soil Moisture = 264
10:36:25.269 -> Wind direction: 248 degrees
10:36:49.600 -> 
10:36:49.600 -> Temperature: 79.30
10:36:49.600 -> Humidity: 31
10:36:49.600 -> Pressure: 88736
10:36:49.600 -> Altitude: 3625.4
10:36:49.600 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:49.637 -> Soil Moisture = 133
10:36:49.637 -> Wind direction: 113 degrees
10:36:49.637 -> Rain click!
10:36:52.666 -> 
10:36:52.666 -> Temperature: 79.30
10:36:52.666 -> Humidity: 31
10:36:52.666 -> Pressure: 88730
10:36:52.666 -> Altitude: 3627.1
10:36:52.666 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:52.666 -> Soil Moisture = 149
10:36:52.666 -> Wind direction: 113 degrees
10:36:55.707 -> 
10:36:55.707 -> Temperature: 79.29
10:36:55.707 -> Humidity: 31
10:36:55.707 -> Pressure: 88735
10:36:55.707 -> Altitude: 3625.6
10:36:55.707 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:55.707 -> Soil Moisture = 270
10:36:55.707 -> Wind direction: 113 degrees
10:36:58.752 -> 
10:36:58.752 -> Temperature: 79.29
10:36:58.752 -> Humidity: 31
10:36:58.752 -> Pressure: 88734
10:36:58.752 -> Altitude: 3625.8
10:36:58.752 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:36:58.752 -> Soil Moisture = 251
10:36:58.752 -> Wind direction: 248 degrees
10:36:58.789 -> Rain click!
10:36:58.789 -> Disturber.
10:37:01.804 -> 
10:37:01.804 -> Temperature: 79.25
10:37:01.804 -> Humidity: 31
10:37:01.804 -> Pressure: 88731
10:37:01.804 -> Altitude: 3626.7
10:37:01.804 -> UV A, B, index: %4.2f, %4.2f, %4.2f
10:37:01.804 -> Soil Moisture = 241
10:37:01.804 -> Wind direction: 248 degrees
```

**Comment by phillipjohnston** [comment]
Now, it may very well be that the interrupt behavior reported in #4 is messing with things.

**Comment by makin-stuff** [comment]
Hi there @phillipjohnston. I would highly recommend checking out the documentation on the weather meter ([hookup guide](https://learn.sparkfun.com/tutorials/weather-meter-hookup-guide?_ga=2.118291529.1974796924.1651765531-2045279763.1566849112) and [datasheet](https://cdn.sparkfun.com/assets/d/1/e/0/6/DS-15901-Weather_Meter.pdf)).

The wind vane basically functions as a voltage divider. So I think you need to read the analog voltage on the WDIR/A1 pin. Then, the voltage divider equation is: Vo = (Vi*R2)/(R1+R2). Vo is measured from A1, Vi = 3.3V, and R1 is 10k (from schematic). You can calculate R2 and look it up in this table from the datasheet and find the corresponding wind direction:
![image](https://user-images.githubusercontent.com/54557724/167030124-357425f8-3bd4-4c1e-a180-dfc104cfbf6e.png)

Hope this helps!

**Comment by phillipjohnston** [comment]
Right, I'm happy to do that myself. I'm just pointing out that the example code doesn't work as expected.

**Comment by phillipjohnston** [comment]
Although, now that I reread the reviews on the product page (https://www.sparkfun.com/products/15901), I see that this behavior is observed by others and maybe that's just the best it can be.

**Comment by santaimpersonator** [comment]
@phillipjohnston
The ADC on the ESP32 is non-linear, which causes issues with the readings. I'd recommend reading and printing out the ADC values, while spinning the wind vane around. If you create a histogram chart (binsize<20), you should be able to see distinct peaks of the indicated directions (which would allow you to fix the example code).

Also, it has a 12-bit ADC (0-4095).
