### ISSUE TITLE
MM_Weather_CB_Test panic if interrupts are enabled.

### ISSUE THREAD

**Issue by phillipjohnston** [sparkfun/MicroMod_Weather_Carrier_Board#4]
After #2, the code compiles without modification. However, the application panics when interrupts are enabled. Commenting it out removes this error.

```
10:32:47.098 -> ++ MbedOS Error Info ++
10:32:47.098 -> Error Status: 0x80FF0144 Code: 324 Module: 255
10:32:47.098 -> Error Message: Assertion failed: status == osOK
10:32:47.098 -> Location: 0x24EE9
10:32:47.098 -> File: mbed-os/rtos/source/ThisThread.cpp+225
10:32:47.098 -> Error Value: 0x0
10:32:47.098 -> Current Thread: main Id: 0x100048E0 Entry: 0x25EF1 StackSize: 0x1000 StackMem: 0x10006560 SP: 0x100074BC 
10:32:47.098 -> For more info, visit: https://mbed.com/s/error?error=0x80FF0144&tgt=SFE_ARTEMIS_MM_PB
10:32:47.134 -> -- MbedOS Error Info --
```

**Comment by makin-stuff** [comment]
Hi there @phillipjohnston. I'm closing this issue because this error has nothing to do with the hardware of the MM Weather CB but with the processor board your are using with it. Can you please repost this issue on the corresponding github repo for the processor you're using? Thank you.
